// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_mcmc_kernel_internal
Rcpp::List rcpp_mcmc_kernel_internal(int M, int burn_in, arma::vec time, arma::vec delta, arma::vec removal, bool is_hybrid, double t_max, double r_star);
RcppExport SEXP _pcsclr_rcpp_mcmc_kernel_internal(SEXP MSEXP, SEXP burn_inSEXP, SEXP timeSEXP, SEXP deltaSEXP, SEXP removalSEXP, SEXP is_hybridSEXP, SEXP t_maxSEXP, SEXP r_starSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time(timeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type removal(removalSEXP);
    Rcpp::traits::input_parameter< bool >::type is_hybrid(is_hybridSEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type r_star(r_starSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_mcmc_kernel_internal(M, burn_in, time, delta, removal, is_hybrid, t_max, r_star));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pcsclr_rcpp_mcmc_kernel_internal", (DL_FUNC) &_pcsclr_rcpp_mcmc_kernel_internal, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_pcsclr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
