# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_mcmc_kernel_internal <- function(M, burn_in, time, delta, removal, is_hybrid, t_max, r_star) {
    .Call(`_pcsclr_rcpp_mcmc_kernel_internal`, M, burn_in, time, delta, removal, is_hybrid, t_max, r_star)
}

